spring.application.name=crm_mini
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/crm_db
spring.datasource.username=postgres
spring.datasource.password=411204
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=y4ApmWGlScTuI4Srk6h/KJwUOVZbU7duGzzIdMvLOGE=
# Access token expiration: 15 minutes (in milliseconds)
jwt.expiration=900000
# Refresh token expiration: 7 days (in milliseconds)
jwt.refresh-expiration=604800000

# Swagger/OpenAPI Configuration 
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
